RequerimientosST/Controllers/APIRequerimientoController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using RequerimientosST.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RequerimientosST.Logic;

namespace RequerimientosST.Controllers
{
    public class APIRequerimientoController : Controller
    {
        // GET: APIRequerimiento
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ObtenerRequerimientosAPI([DataSourceRequest] DataSourceRequest request)
        {
            try
            {

                string responseBody = APILogic.ObtenerRequerimientoAPI("http://localhost/RequerimientoSTApi/api/Requerimientos/ObtenerRequerimientos");
                List<uspObtenerRequerimientos_Result> ObjOrderList = JsonConvert.DeserializeObject<List<uspObtenerRequerimientos_Result>>(responseBody);
                var ObjOrderList2 = JsonConvert.DeserializeObject<List<uspObtenerRequerimientos_Result>>(responseBody);
                DataSourceResult result = ObjOrderList2.ToList().ToDataSourceResult(request);
                return Json(result);


            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

    }
}

RequerimientosST/Controllers/RegistroRequerimientoController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RequerimientosST.Models;
using System.Threading;
using System.Globalization;
using Kendo.Mvc.Extensions;
using System.Net;
using System.IO;
using Newtonsoft.Json;

namespace RequerimientosST.Controllers
{
    public class RegistroRequerimientoController : Controller
    {
        // GET: RegistroRequerimiento
        public ActionResult Index()
        {
          
            return View();

        }

        public JsonResult ObtenerAreaLista()
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {

                    var resultado = DB.uspObtenerMaestroArea().ToList();
                    List<Object> viewModel = new List<object>();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(new
                        {
                            Id = resultadoItem.Id,
                            Nombre = resultadoItem.Nombre
                        });
                    }

                    // DataSourceResult result = viewModel.ToDataSourceResult(request);

                    return Json(viewModel, JsonRequestBehavior.AllowGet);

                }

            }

            catch (Exception ex)
            {
                //return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }
            return Json(100);
        }

        public JsonResult ObtenerPrioridadLista()
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {

                    var resultado = DB.uspObtenerMaestroPrioridad().ToList();
                    List<Object> viewModel = new List<object>();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(new
                        {
                            Id = resultadoItem.Id,
                            Prioridad = resultadoItem.Prioridad
                        });
                    }


                    return Json(viewModel, JsonRequestBehavior.AllowGet);

                }

            }

            catch (Exception ex)
            {
                //return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }
            return Json(100);
        }

        public JsonResult ObtenerIngenieroLista()
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {

                    var resultado = DB.uspObtenerMaestroIngeniero().ToList();
                    List<Object> viewModel = new List<object>();
                    foreach (var resultadoItem in resultado)
                    {
                        viewModel.Add(new
                        {
                            Id = resultadoItem.Id,
                            Ingeniero = resultadoItem.Ingeniero
                        });
                    }


                    return Json(viewModel, JsonRequestBehavior.AllowGet);

                }

            }

            catch (Exception ex)
            {
                //return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }
            return Json(100);
        }


        public ActionResult ObtenerRequerimientos([DataSourceRequest] DataSourceRequest request)
        {
            try
            {

                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {

                    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

                    IQueryable<uspObtenerRequerimientos_Result> obtenerRequerimientosLista = (IQueryable<uspObtenerRequerimientos_Result>)DB.uspObtenerRequerimientos().AsQueryable();
                    DataSourceResult result = obtenerRequerimientosLista.ToList().ToDataSourceResult(request);
                    return Json(result);

                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

      

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CrearRegistroRequerimiento([DataSourceRequest] DataSourceRequest request, uspObtenerRequerimientos_Result requerimientoEdit)
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {


                    if (requerimientoEdit != null && ModelState.IsValid)
                    {
                        DB.uspGuardarRequerimientos(
                            requerimientoEdit.Nombre,
                            requerimientoEdit.Aplicativo,
                            requerimientoEdit.Alcance,
                            requerimientoEdit.FechaSolicitud,
                            requerimientoEdit.Prioridad,
                            requerimientoEdit.Ingeniero,
                            requerimientoEdit.DiasDesarrollo,
                            requerimientoEdit.FechaDesarrollo);
                        DB.SaveChanges();
                    }

                    return Json(new[] { requerimientoEdit }.ToDataSourceResult(request, ModelState));



                }

            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ActualizarRequerimiento([DataSourceRequest] DataSourceRequest request, uspObtenerRequerimientos_Result requerimientoEdit)
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {

                    if (requerimientoEdit != null && ModelState.IsValid)
                    {
                        DB.uspActualizarRequerimientos(
                            requerimientoEdit.Id,
                            requerimientoEdit.Nombre,
                            requerimientoEdit.Aplicativo,
                            requerimientoEdit.Alcance,
                            requerimientoEdit.FechaSolicitud,
                            requerimientoEdit.Prioridad,
                            requerimientoEdit.Ingeniero,
                            requerimientoEdit.DiasDesarrollo,
                            requerimientoEdit.FechaDesarrollo);
                        DB.SaveChanges();
                    }

                    return Json(new[] { requerimientoEdit }.ToDataSourceResult(request, ModelState));


                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EliminarRequerimiento([DataSourceRequest] DataSourceRequest request, uspObtenerRequerimientos_Result referenciasEdit)
        {
            try
            {
                using (var DB = new PruebaTecnicaJulianArangoEntities())
                {


                    if (referenciasEdit != null && ModelState.IsValid)
                    {
                        DB.uspEliminarRequerimientos(referenciasEdit.Id);
                        DB.SaveChanges();
                    }

                    return Json(new[] { referenciasEdit }.ToDataSourceResult(request, ModelState));



                }

            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(550, "Some error" + ex.Message);
            }

        }


    }
}

RequerimientosST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Requerimiento ST</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Scripts.Render("~/bundles/jquery")
    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.common-bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.aspnetmvc.min.js"></script>
    <script>kendo.culture("es-ES");</script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Requerimiento ST", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Requerimientos", "Index", "RegistroRequerimiento")</li>
                    <li>@Html.ActionLink("Requerimientos API", "Index", "APIRequerimiento")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer" style="text-align:center">
            <div class="container-fluid">
                <p>@DateTime.Now.Year - JAC</p>
            </div>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>